### ISSUE TITLE
compilation error on E0.23 and efl 1.23.3

### ISSUE THREAD

**Issue by chrisripp** [simotek/Enlightenment-Themes#1]
Hello, and thank you for your script.
With E0.23 there is a compilation error. I downloaded the 3 Darkmod-color-config.conf kitty, ice and green mod.
This does not work for themes, but it's ok for terminology.
If you could update for E23 this will be super cool
"Creating theme
edje_cc: Error. edc-dm/elm/check.edc:96 color code should start with '#' and have 4 or 8 digit hex number. (3 or 6 digits are allowed to omit alpha value of 255)
Failed command:
mv -v img-manual-bak/* img-manual-convd
mv: impossible d'évaluer 'img-manual-bak/*': Aucun fichier ou dossier de ce type
Failed command:
cp Extra-Dark-Green.edj /home/guest/.elementary/themes
cp: impossible d'évaluer 'Extra-Dark-Green.edj': Aucun fichier ou dossier de ce type"

**Comment by triki1** [comment]
Ok it's all good I tested with Darkmod-color base, it's all good.
These are just the green, kitty, and ice examples that do not compile.
Thank you for your script is great.
BRAVO;)

**Comment by simotek** [comment]
All the branches should be working now as far as I know. As a bonus there is a couple of more themes that I am working on that are in a very usable state that i'd love to get further testing on for them look at the `Vertex` and `Cerium2` branches, both are at a point where i'm happy using them daily but there are likely things I don't use that don't work as well yet and I'd love some bug reports here on stuff people want fixed especially on vertex which will become the base for several other themes in the near future. Vertex has the bonus of a mostly matching GTK theme.

You can also play around with the themes in anti-transient-color, transient-color and Transient (be warned the last 2 might eat alot of CPU) and feel free to report stuff but it might be a little while until I get to them because they are a little less of a priority.

Cheers

Simon

1. https://github.com/horst3180/vertex-theme
